function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(6)=1/(params(2)*params(7)^(params(5)*(1-params(3))-1))-(1-params(4));
    zeta=params(7)*params(1)/ys_(6);
    eta=zeta*(params(4)+params(6))/params(7);
    ys_(5)=(1-params(1))/(1-params(1)+(1-params(5))/params(5)*(1-eta));
    C=(exo_(1)*zeta^params(1)*params(7)^(-params(1)))^(1/(1-params(1)));
    kappa=params(7)*params(13)/(params(6)+params(8));
    a=kappa*params(11)/(1-params(1));
    D=ys_(5)*C*(params(10)*exp(params(11)*params(12)))^(1/(1-params(1)));
    ys_(7)=1/a*lambertw(a*D);
    ys_(13)=params(10)*exp((-params(11))*(kappa*ys_(7)-params(12)));
    ys_(3)=zeta*ys_(7);
    ys_(2)=eta*ys_(7);
    ys_(1)=ys_(7)-ys_(2);
    ys_(4)=(1-params(1))*ys_(7)/ys_(5);
    ys_(8)=ys_(7)/ys_(13);
    ys_(12)=params(13);
    ys_(10)=ys_(7)*ys_(12);
    ys_(11)=kappa*ys_(7);
    ys_(9)=(1-ys_(5))^(1-params(5))*params(5)*(ys_(1)^params(5)*(1-ys_(5))^(1-params(5)))^(-params(3))*ys_(1)^(params(5)-1);
    % Auxiliary equations
end
