function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(6)=(1+exo_(3))*(1/(params(2)*params(7)^(params(5)*(1-params(3))-1))-(1-params(4)))/(1-exo_(6));
    zeta=params(7)*params(1)*(1-exo_(7))/ys_(6);
    phi=exo_(1)^(1/(1-params(1)))*(params(1)*(1-exo_(7))/ys_(6))^(params(1)/(1-params(1)));
    ys_(4)=(1-exo_(7))*(1-params(1))*phi/(1+exo_(5));
    eta=zeta*(params(4)+params(6))/params(7);
    kappa=ys_(4)*params(5)/(1-params(5))*(1-exo_(4))/(1+exo_(2));
    a0=exo_(2)*kappa+exo_(8);
    a1=kappa*(-exo_(2))+phi*exo_(3)*eta+ys_(4)*(exo_(5)+exo_(4))+phi*zeta*exo_(6)*ys_(6)/params(7)+exo_(7)*phi;
    ys_(5)=(kappa+a0)/(phi+kappa-phi*eta-a1);
    ys_(7)=phi*ys_(5);
    ys_(1)=kappa*(1-ys_(5));
    ys_(3)=zeta*ys_(7);
    ys_(2)=eta*ys_(7);
    ys_(9)=a0+a1*ys_(5);
    ys_(8)=(1-ys_(5))^(1-params(5))*params(5)*(ys_(1)^params(5)*(1-ys_(5))^(1-params(5)))^(-params(3))*ys_(1)^(params(5)-1);
    ys_(12)=params(10);
    ys_(10)=ys_(7)*ys_(12);
    ys_(11)=ys_(10)/(1-(1-params(8))/params(7));
    % Auxiliary equations
ys_(13)=exo_(2);
ys_(14)=exo_(6);
ys_(15)=exo_(3);
end
